<template>
  <section class="surface hero">
    <div class="stack">
      <span class="eyebrow">Nuxt 4 starter</span>
      <h1>Ship a Nuxt app with structure on day one.</h1>
      <p class="muted copy">
        This project was generated by NuxtKit Pro with a production-ready layout,
        a layered CLI workflow, and feature packs you can compose as needed.
      </p>

      <div class="actions">
        <NuxtLink class="button" to="/api-demo">
          Explore demo routes
        </NuxtLink>
        <NuxtLink class="button secondary" to="/account">
          Open account route
        </NuxtLink>
      </div>
    </div>

    <div class="grid stats">
      <article class="stat-card">
        <strong>Templates</strong>
        <p class="muted">Default, dashboard, landing, and SaaS starter experiences.</p>
      </article>
      <article class="stat-card">
        <strong>Feature packs</strong>
        <p class="muted">Auth, API, Tailwind, and linting install cleanly on top.</p>
      </article>
      <article class="stat-card">
        <strong>Scaffold flow</strong>
        <p class="muted">Base files, template overrides, and feature merges are applied safely.</p>
      </article>
    </div>
  </section>
</template>

<style scoped>
.hero {
  display: grid;
  grid-template-columns: minmax(0, 1.2fr) minmax(280px, 0.8fr);
  gap: 1.5rem;
  padding: 2rem;
}

h1 {
  margin: 0;
  font-size: clamp(2.4rem, 6vw, 4.5rem);
  line-height: 0.96;
  letter-spacing: -0.06em;
}

.copy {
  max-width: 56ch;
  font-size: 1.05rem;
}

.actions {
  display: flex;
  flex-wrap: wrap;
  gap: 0.75rem;
}

.stats {
  align-content: start;
}

@media (max-width: 900px) {
  .hero {
    grid-template-columns: 1fr;
  }
}
</style>
